/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GeneScope } from "./GeneScope";
export * as factories from "./factories";
export { GeneScope__factory } from "./factories/GeneScope__factory";
